Add youtube hls streaming wip
ushadow/obs-studio pull request #6
Opened 2020-06-10 04:43 UTC by mv2731

This pull request includes the changes made to support HLS ingestion streaming to YouTube. I added an obs_ouptut_info struct and registered it in order to make this possible and then wrote the corresponding methods for the struct. Additionally, I added parameters so that start and init functions could recognize the output format as HLS.

2020-06-10 14:30 UTC, ushadow commented on plugins/obs-ffmpeg/obs-ffmpeg-mux.c
> +	info("Writing file '%s'...", stream->path.array);
Writing file -> Writing to path

2020-06-10 14:58 UTC, ushadow commented on plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
>  	    strncmp(ffm->params.file, TCP_PROTO, sizeof(TCP_PROTO) - 1) == 0)
Add a check for HTTP protocol here as well.

2020-06-10 14:59 UTC, ushadow commented on plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
>  	    strncmp(ffm->params.file, TCP_PROTO, sizeof(TCP_PROTO) - 1) == 0)
Then if isNetwork is true, call avformat_network_init().

If isNetwork is true and format is not set, guess format to be "mpegts", else if format is set, guess format to be format.

2020-06-10 15:42 UTC, ushadow commented on plugins/obs-ffmpeg/obs-ffmpeg-mux.c
> +		stream->format = "";
I don't see where stream->format is set in the command line.

2020-06-10 15:47 UTC, ushadow requested changes
Please see the comments.

2020-06-10 20:15 UTC, ushadow commented on plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
> -
Don't remove the empty line here and the one below.

2020-06-10 20:33 UTC, mv2731 commented on plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
> -
Done.

2020-06-10 21:30 UTC, ushadow commented on plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
> +	bool isHTTP = false;
bool is_http = (strncmp(ffm->params.file, HTTP_PROTO,
			  sizeof(HTTP_PROTO) - 1) == 0);

2020-06-10 21:31 UTC, ushadow commented on plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
>  	bool isNetwork = false;
isNetwork -> is_network

2020-06-10 21:32 UTC, ushadow commented on plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
>  		output_format = av_guess_format("mpegts", NULL, "video/M2PT");
!is_http

2020-06-11 18:28 UTC, ushadow commented on plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
> +			  sizeof(HTTP_PROTO) - 1) == 0);
Add a space before sizeof to align with ffm.

2020-06-11 18:37 UTC, ushadow commented on plugins/obs-ffmpeg/obs-ffmpeg-mux.c
> +	dstr_free(&path);
Move dstr_free(&path); to after start_pipe(stream, path.array);

2020-06-11 18:38 UTC, ushadow commented on plugins/obs-ffmpeg/obs-ffmpeg-mux.c
> +	settings = obs_output_get_settings(stream->output);
We don't really need settings.

2020-06-11 18:39 UTC, ushadow commented on plugins/obs-ffmpeg/obs-ffmpeg-mux.c
> +	obs_service_t *service;
Move obs_service_t *service; to the beginning where all the variables are declared.

2020-06-11 20:05 UTC, ushadow commented on plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
> +	printf("info: output_format name and long_name: %s, %s\n",
Check if output_format->name or output_format->long_name is NULL. You can do something like:
output_format->name ? output_format->name : "unknown"

2020-06-11 20:06 UTC, ushadow requested changes
One more small change.

2020-06-11 20:51 UTC, ushadow commented on plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
> +	output_format->name ? output_format->name : "unknown";
These need to be in the printf statement.

printf("info: output_format name and long_name: %s, %s\n",
           output_format->name ? output_format->name : "unknown",
           output_format->long_name ? output_format->long_name : "unknown");

2020-06-11 20:52 UTC, ushadow requested changes
Please see the comment.

2020-06-11 21:21 UTC, merged